# Generated by Django 5.1.7 on 2025-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('mg', 'miligrams'), ('ml', 'mililiters'), ('l', 'liters'), ('pcs', 'pieces'), ('oz', 'ounce'), ('lb', 'pound')], default='pcs', max_length=100),
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
