# Generated by Django 5.1.7 on 2025-04-06 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foodlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('expirationDate', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'gramy'), ('kg', 'kilogramy'), ('ml', 'mililitry'), ('l', 'litry'), ('szt', 'sztuki'), ('opak', 'opakowanie')], default='szt', max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('openDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('fresh', 'Świeże'), ('opened', 'Otwarte'), ('expired', 'Przeterminowane'), ('used', 'Zużyte')], default='fresh', max_length=100)),
                ('reminder', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodList',
        ),
    ]
