# Generated by Django 5.1.7 on 2025-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_delete_foodlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='openDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
